language: minimal

services:
  - docker

env:
  global:
    - DOCKER_API_IMAGE=$DOCKER_USER/time-manager-api
    - DOCKER_FRONT_IMAGE=$DOCKER_USER/time-manager-front
    - VM_USER=travis
    - VM_IP=34.122.33.216
    - DEPLOY_PATH=/home/travis/TIME_MANAGER_THJ

stages:
  - name: build & push images
  - name: deploy
    if: branch = dev_ops_bootstrap

jobs:
  include:
    # Stage 1 — Build & Push des 2 images
    - stage: build & push images
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t $DOCKER_API_IMAGE:$TRAVIS_COMMIT ./time_manager
        - docker tag $DOCKER_API_IMAGE:$TRAVIS_COMMIT $DOCKER_API_IMAGE:latest
        - docker push $DOCKER_API_IMAGE:$TRAVIS_COMMIT
        - docker push $DOCKER_API_IMAGE:latest
        - docker build -t $DOCKER_FRONT_IMAGE:$TRAVIS_COMMIT ./frontend
        - docker tag $DOCKER_FRONT_IMAGE:$TRAVIS_COMMIT $DOCKER_FRONT_IMAGE:latest
        - docker push $DOCKER_FRONT_IMAGE:$TRAVIS_COMMIT
        - docker push $DOCKER_FRONT_IMAGE:latest

    # Stage 2 — Deploy
    - stage: deploy
      before_script:
        - echo "$SSH_KEY_BASE64" | base64 -d > /tmp/deploy_key
        - chmod 600 /tmp/deploy_key
      script:
        - scp -i /tmp/deploy_key -o StrictHostKeyChecking=no docker-compose.yml $VM_USER@$VM_IP:$DEPLOY_PATH/
        - ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $VM_USER@$VM_IP "
            cd $DEPLOY_PATH &&
            DOCKER_USER=$DOCKER_USER docker compose pull &&
            DOCKER_USER=$DOCKER_USER docker compose up -d
          "